#!/bin/sh

USERAGENT="Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.85 Safari/537.36"

download () {
	read -p "Please enter your query: " SEARCH
	QUERY=$(echo "$SEARCH" | sed -e "s/ /+/g")
	curl -A "$USERAGENT" -so .search.html "https://nyaa.si/?f=0&c=0_0&q=$QUERY"
	SELECTION="$(grep -Po '(?<= title=").*(?=</a>)' .search.html | sed 's/">.*//g' | sed "s/&#39;/'/g" | sed "1,5d" | sort | fzf -e | sed "s/'/&#39;/g")"
	if [ "$SELECTION" = "" ]; then
		echo "Nothing selected! Exiting..."
		exit
	fi
	MAGNET="$(curl -A "$USERAGENT" -s "https://nyaa.si/$(grep -F "$SELECTION" .search.html | grep -Po "view/[0-9]{7}")" | grep magnet | sed -r 's/.*(magnet:[^"]*).*/\1/g')"
	rm .search.html
	transmission-cli "$MAGNET"
}

nyaa_help () {
	printf 'Nyaa.si CLI Downloader (nyaa) by swindlesmccoop\n\nUsage: nyaa [-d]\n-d, --download: Start (d)ownload function to enter query\n-h, --help: Print this (h)elp message\n'
	exit 1
}

#if no parameters are supplied, print help
if [ $# -eq 0 ]; then nyaa_help; fi

case $1 in
	-d) download ;;
	--download) download ;;
	-h) nyaa_help ;;
	--help) nyaa_help ;;
esac
